### ISSUE TITLE
Plugin without SBC

### ISSUE THREAD

**Issue by aceycv8** [Kriechi/duet-plugin-filament-load-cell#2]
Hi guys

Could this be done without an SBC and have an Arduino / ESP pushing the results via http for the plugin to pickup

**Comment by Kriechi** [comment]
Probably yes. You could call the Duet RepRapFirmware API directly and set the weight value as a global variable, and then read it with a DWC plugin. It's a completely different approach than used in this project though. 

I recommend jumping on the Duet forums - maybe somebody built something similar already.

**Comment by aceycv8** [comment]
thanks Kriechi - i will have a pole around
